---
abstract: 'A very easy interface to YouTube.'
author:
  - "Șuteu \"Trizen\" Daniel <trizenx@gmail.com>"
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4008, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-YoutubeViewer
provides:
  WWW::YoutubeViewer:
    file: lib/WWW/YoutubeViewer.pm
    version: 0.05
  WWW::YoutubeViewer::GetCaption:
    file: lib/WWW/YoutubeViewer/GetCaption.pm
    version: 0.01
  WWW::YoutubeViewer::Itags:
    file: lib/WWW/YoutubeViewer/Itags.pm
    version: 0.02
  WWW::YoutubeViewer::ParseXML:
    file: lib/WWW/YoutubeViewer/ParseXML.pm
    version: 0.03
  WWW::YoutubeViewer::RegularExpressions:
    file: lib/WWW/YoutubeViewer/RegularExpressions.pm
    version: 0.01
  WWW::YoutubeViewer::Utils:
    file: lib/WWW/YoutubeViewer/Utils.pm
    version: 0.02
recommends:
  Term::ReadKey: 0
  Term::ReadLine::Gnu::XS: 0
  XML::Fast: 0
requires:
  Data::Dump: 0
  File::Path: 0
  File::Spec::Functions: 0
  Getopt::Long: 0
  HTTP::Request: 0
  LWP::UserAgent: 0
  Term::ANSIColor: 0
  Term::UI: 0
  Text::ParseWords: 0
  Text::Wrap: 0
  URI::Escape: 0
  perl: 5.016
resources:
  license: http://dev.perl.org/licenses/
version: 0.05
